### ISSUE TITLE
Passing timeout to queued job

### ISSUE THREAD

**Issue by ErikEvenson** [rq/django-rq#16]
Is it possible to pass a timeout value to an enqueued job?  I believe the default is 180 seconds -- which is short for some long-running jobs.

Thanks for the great tool!

**Comment by ccurvey** [comment]
update  for those of you finding this page from a search engine.  The `timeout` parameter is now called `job_timeout`.  So the proper syntax is:

    queue.enqueue(populate_trends, args=(self,), timeout=500)

**Comment by extremoburo** [comment]
@ccurvey = saviour
