### ISSUE TITLE
tests fail with working runtime given worker or async=false

### ISSUE THREAD

**Issue by davidthewatson** [rq/django-rq#221]
I am using django-rq==0.9.4.

I have test code such as this:

    from django.test import TestCase
    from django.core.management import call_command
    from django_rq import get_worker

    from crawl.models import FileResource, JsonResource

    class LocalFeedCommandTestCase(TestCase):
        fixtures = ['apartmentlistfeed', 'apartmentlistsourcetypes']

        def test_ingest_feeds(self):
            call_command('ingest_local_feeds')
            file_resource = FileResource.objects.get()
            self.assertIsInstance(file_resource, FileResource)
            json_resource = JsonResource.objects.get()
            self.assertIsInstance(json_resource, JsonResource)

The code fails on the file_resource line if I use the method under "Synchronous mode" in the README or it fails on the json_resource line if I use the "Testing tip". The code runs without exception at normal runtime.

Is there any testing method that will work under django 1.10? 

My @job functions are fired with the delay method from django signals and look like this:

    @job
    def process_feed_file(instance):
        parsed_json = json.loads(instance.source_file.read().decode('utf-8'))
        for p in parsed_json['properties']:
            try:
                json_item = JsonResourceItem()
                json_item['file_resource'] = instance
                json_item['json'] = p
                json_item.save()
                logging.info('SAVED JSON ITEM: {}'.format(instance))
            except Exception as e:
                logging.info('EXCEPTION: {}'.format(e))
                raise DropItem

**Comment by selwin** [comment]
What's the exception?
