### ISSUE TITLE
example how to use for bulk_create

### ISSUE THREAD

**Issue by pmtolk** [rq/django-rq#236]
I was wondering if you could provide some guidance on how to use django-rq for a bulk_create operation.

When numerous requests come in to add data to a database, how would you queue the requests model data by using rq to store the data in redis? And then get a bunch at once on a timer and every minute insert all the records?

https://docs.djangoproject.com/en/1.11/ref/models/querysets/#bulk-create

**Comment by lucastamoios** [comment]
Are you asking for something like [this](https://github.com/nvie/rq/issues/241)? If so, I think it will only be possible when [this PR](https://github.com/nvie/rq/pull/553) is accepted.

**Comment by pmtolk** [comment]
In the integration_app [views.py](https://github.com/ui/django-rq/blob/master/integration_test/integration_app/views.py)

```
if request.method == 'POST':
        django_rq.enqueue(add_mymodel, request.POST["name"])
```

it is saving every model on POST because the models.py has
```
def add_mymodel(name):
    m = MyModel(name=name)
    m.save()
```

But I do not want to call m.save() on each insert into a database

Rather I want store the request.POST["name"] in redis, using redis as a cache like so
```
import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0);
r.sadd('MyModel', 'a')
r.sadd('MyModel', 'b')
r.sadd('MyModel', 'c')
```
And then every minute do a bulk_create

```
insert_list = r.sscan('MyModel')
MyModel.objects.bulk_create(insert_list)
r.del('MyModel')
```

Am I able to use django-rq to accomplish something like this and what would you recommend the best method is?

Thanks

**Comment by lucastamoios** [comment]
This is beyond of my knowledge. Sorry. :(

**Comment by selwin** [comment]
@pmtolk as @lucastamoios mentioned, we can only build this into Django-RQ when https://github.com/nvie/rq/pull/553/files is merged into RQ. Would appreciate someone taking over that PR it just needs some minor modifications before i's ready to be merged.

**Comment by selwin** [comment]
There's currently no way to enqueue jobs in bulk to RQ.
