### ISSUE TITLE
manage command fails in example app with empty database - 'relation "integration_app_mymodel" does not exist'

### ISSUE THREAD

**Issue by therefromhere** [rq/django-rq#247]
With an empty database, the `integration_test` app manage.py fails with this error:

```
django.db.utils.ProgrammingError: relation "integration_app_mymodel" does not exist
LINE 1: ...odel"."id", "integration_app_mymodel"."name" FROM "integrati...

```
To reproduce:

drop/create database as per `integration_test/README.md`
```
cd integration_test
./manage.py
# or
./manage.py migrate
```

Note that ./manage.py fails, even before running commands.

This occurs on python 2.7 and python 3.6, and with Django 1.10 and 1.11.

The cause seems to be this from `integration_test/integration_app/models.py`

```
# causes a DB connection at import-time
# see TestIntegration.test_worker_lost_connection
list(MyModel.objects.all())
```
(removing that line resolves the issue)

That code was added in 67fb7debcc9b020a52d212bdf92788dd5928744e by @depaolim in relation to #216  - is it not possible to test hit the tested issue in another way?

**Comment by selwin** [comment]
The tests run fine on Travis. Closing this issue.
