### ISSUE TITLE
Unable to update model from job while testing

### ISSUE THREAD

**Issue by sean-dooher** [rq/django-rq#277]
I am having trouble testing a job that modifies and saves the model. In the debugger, I can evaluate code inside of the job and run refresh_from_db() and it seems like it works, but once the job function returns the results are lost. It does work in a non-testing environment, but I'd prefer to be able to test my code.

I figure this has something to do with django's testing database setup, but I have been unable to find a solution so far. I have managed to make a simple test case that reproduces the error below.

I have the following django_rq job function that I have created.
```
@job
def simple_job(model)
    model.num = 100
    model.save()
```

For the following model:
```
class Model1(models.Model):
    num = models.IntegerField()
```

This is my test that is failing
```
def test_model(self):
	model1 = Model1(num=0)
	model1.save()

	simple_job.delay(model1) # also doesn't work using enqueue
	get_worker().work(burst=True)

	model1.refresh_from_db()

	self.assertEqual(model1.num, 100) # Fails with 0 != 100
```

**Comment by sean-dooher** [comment]
I managed to get my test working by adding a alternative get_worker method that uses SimpleWorker from rq. Maybe this could be added to workers.py as a method? I'll submit a PR if that sounds like a good idea

```
def get_test_worker(*queue_names, **kwargs):
    """
    Returns a RQ worker for all queues or specified ones.
    """
    queues = get_queues(*queue_names)
    name = kwargs.get('name')
    return SimpleWorker(queues, connection=queues[0].connection, name=name)
```

**Comment by selwin** [comment]
It could be that your tests run on SQLite which is single threaded, which is why RQ's default worker (which calls `os.fork()` when performing jobs can't update your DB).

A good solution would be to modify `get_worker()` to accept `worker_class` kwarg so you could do `get_worker('default', worker_class=SimpleWorker)`.

Please submit a pull request for this (and mention this  on README).

**Comment by mkerins** [comment]
In my case jobs are queued as a result of post_save signals so it didn't make much sense to test calling them directly like in the docs. I had to do two things to get unit tests to work without an redis instance running. Like many Django projects, I have a base settings file that is imported by production and testing specific settings file. The testing settings uses SQLite so threading doesn't interfere.

In testing settings file:
```
from .base import *  # noqa
from fakeredis import FakeRedis, FakeStrictRedis
import django_rq.queues

# Credit to @zyv, adapted from https://github.com/rq/django-rq/issues/106#issuecomment-367674954
django_rq.queues.get_redis_connection = lambda _, strict: FakeStrictRedis() if strict else FakeRedis()

for config in RQ_QUEUES.values():
    config["ASYNC"] = False
```

The unit tests don't need to create a special worker and an actual redis instance is not required. In the jobs file:
```
...
import django_rq

q = django_rq.get_queue('default')
```

**Comment by selwin** [comment]
You should use RQ's `SimpleWorker` class that doesn't call `os.fork()` when running the jobs.

**Comment by lifenautjoe** [comment]
So what is the solution to this? Did the change to `get_worker()` ever happened?
