### ISSUE TITLE
Problem with url include in Django 2.0.3

### ISSUE THREAD

**Issue by koddr** [rq/django-rq#279]
Hello.

*Is there really support for Django 2.x?!* I want to use Django-RQ in Django `2.0.3`, but if I include url to my `urls.py`, I have error (I'm using Pipenv `11.7.1`):

```bash
File "/Users/user/.local/share/virtualenvs/myproject-fiOUaYzG/lib/python3.6/site-packages/django_rq/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

On `.../lib/python3.6/site-packages/django_rq/urls.py` we're have old style url's paths and (probably) deprecated in `2.x` method `patterns`:

```python
from django.conf.urls import patterns, url

urlpatterns = patterns('django_rq.views',
    url(r'^$', 'stats', name='rq_home'),
    url(r'^queues/(?P<queue_index>[\d]+)/$', 'jobs', name='rq_jobs'),
    url(r'^queues/(?P<queue_index>[\d]+)/finished/$',
        'finished_jobs', name='rq_finished_jobs'),
    url(r'^queues/(?P<queue_index>[\d]+)/started/$',
        'started_jobs', name='rq_started_jobs'),
    url(r'^queues/(?P<queue_index>[\d]+)/deferred/$',
        'deferred_jobs', name='rq_deferred_jobs'),
    url(r'^queues/(?P<queue_index>[\d]+)/empty/$', 'clear_queue', name='rq_clear'),
    url(r'^queues/(?P<queue_index>[\d]+)/(?P<job_id>[-\w]+)/$', 'job_detail',
        name='rq_job_detail'),
    url(r'^queues/(?P<queue_index>[\d]+)/(?P<job_id>[-\w]+)/delete/$',
        'delete_job', name='rq_delete_job'),
    url(r'^queues/actions/(?P<queue_index>[\d]+)/$',
        'actions', name='rq_actions'),
    url(r'^queues/(?P<queue_index>[\d]+)/(?P<job_id>[-\w]+)/requeue/$',
        'requeue_job_view', name='rq_requeue_job'),
)
```

How to solve this? Help please.

**Comment by selwin** [comment]
Pull request welcome :)

**Comment by koddr** [comment]
@selwin my PR may broken Django `1.11.x` and lower support of `django-rq`, because new version of Django (2.x) use only `path` instead of `url`.

**Comment by selwin** [comment]
I’ll only merge PRs that supports both Django 1.11 and 2.0. The release notes mentions that:

The django.conf.urls.url() function from previous versions is now available as django.urls.re_path(). The old location remains for backwards compatibility, without an imminent deprecation. The old django.conf.urls.include()function is now importable from django.urls so you can use from django.urls import include,path, re_path in your URLconfs.

https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax

So we should probably try to import re_path (Django 2.0) and fallsback to path (Django < 2.0).

**Comment by koddr** [comment]
@selwin Okay, I'll try today :)

Btw, without including paths to `urls.py` everything is working great — my two Django 2.x projects on production used it.

**Comment by koddr** [comment]
And here it is: #281
