### ISSUE TITLE
DeprecationWarning: 'async' and 'await' will become reserved keywords in Python 3.7

### ISSUE THREAD

**Issue by OrDuan** [rq/django-rq#284]
Since there are few places that `async` keyword is used, we get this warning, which means RQ will break on 3.7.

Here is what PEP8 advised to do in these cases:

> single_trailing_underscore_: used by convention to avoid conflicts with Python keyword, e.g.
> 
> Tkinter.Toplevel(master, class_='ClassName')

I would open a PR to change it to `async_`  but this will be breaking change, what do you guys think?

**Comment by selwin** [comment]
@OrDuan I don't like the aesthetics of the trailing underscore. Two alternatives I can think of:

* Changing `async` to `sync` (the meaning will be inverted)
* Changing `async` to `asynchronous`

Do you mind opening this issue in RQ's github repository? We should change this in RQ before django-rq follows suit.

**Comment by dbinetti** [comment]
Obviously @selwin you know it's been updated in `rq`, but for everyone else's benefit has been updated to `is_async` and released in `0.12.0`.

**Comment by selwin** [comment]
Closing this in favor of https://github.com/rq/django-rq/issues/284
