### ISSUE TITLE
Any advice on how to run a django-rq worker on AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by jacobevans** [rq/django-rq#286]
Elastic beanstalk uses WSGI to serve web apps, so my .config file has something like this:

    option_settings:
      aws:elasticbeanstalk:container:python:
        WSGIPath: widget/wsgi.py

Is there a way to run a django-rq worker with the same approach?

**Comment by esorribas** [comment]
Same problem here... I don't know how to run a rq worker in AWS EB

**Comment by theiosdevguy** [comment]
I even posted a question on Stackoverflow with a bounty raised. No answers yet. Requesting the community and experts to please help

https://stackoverflow.com/questions/49778627/django-rq-and-rqscheduler-deployment-on-aws-elastic-beanstalk

**Comment by johnhuffsmith** [comment]
We've used this pattern to setup celery workers on EB via supervisor: https://stackoverflow.com/questions/41161691/how-to-run-a-celery-worker-with-django-app-scalable-by-aws-elastic-beanstalk

Just sub in the rq worker command and should be good to go.

**Comment by jacobevans** [comment]
@johnhuffsmith I've seen a few blog posts/SO answers with solutions like that, and it seems like a functional solution.

That said, I don't feel like a setup like that really makes sense--EB isn't telling you not to do stuff like that, but it isn't really supported by any of the EB systems.  Basically, you're running an EB instance like a non-EB EC2 instance, but with less control over the overall environment.  You get your source deployed, and your initialization scripts called, but there's nothing built into the EB control panel or APIs to support that kind of functionality (other than SSHing in and looking yourself, of course).

If you could run django-rq as a WSGI app, then you'd be able to set up a separate EB environment, like you would for a standard EB worker tier environment, and be able to take full advantage of EB's built-in monitoring, etc.  Plus, you could scale your workers based on workload, not along with web load.

**Comment by johnhuffsmith** [comment]
You're correct; in my experience it's an uphill battle getting EB to do anything outside it's design.  You will quickly need to fall down to EC2-like manual tweaking on the boxes (package installs, pre/post deploy tasks/apache configs).  You can script it all with .ebextensions, but it's fragile and you'll need to figure all of it out on your own.

If you want that level of deep integration, you'll need to let the infrastructure service you choose dictate the application design details. Either ditch RQ and use the native EB worker daemon via SQS, roll something custom, or explore other hosting options (Heroku, EKS, etc)

**Comment by selwin** [comment]
This is not an issue with django-rq itself. Closing.

**Comment by ronnielivingsince1994** [comment]
@selwin I understand there is nothing wrong with django-rq in this particular issue. However wouldn't it be really great if anyone from the community could extend the **README.rst** with this, I mean you guys have already added deployment steps for Ubuntu and Heroku, why not extend it to AWS as well?!

**Comment by selwin** [comment]
I’m open to accepting pull requests to improve our documentation. Please open one and I’ll take a look at it :)
