### ISSUE TITLE
rqscheduler does not use TIMEOUT set in settings.py

### ISSUE THREAD

**Issue by nmiletic** [rq/django-rq#292]
Hello,

It seems that rqscheduler does not use TIMEOUT set in settings.py.
when Queue instance is returned using from_queue key timeout is not set and default of 180sec is used it seems. 

Thanks
Nemanja

**Comment by selwin** [comment]
Could you please open a PR for this?

**Comment by simone6021** [comment]
+1 for this: really appreciated and needed.

@nmiletic, i am available to complete this PR.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/332
