### ISSUE TITLE
Version in PyPI is 1.2.0, but version in GitHub is 1.1.1

### ISSUE THREAD

**Issue by Flimm** [rq/django-rq#298]
The latest version on PyPI is named 1.2.0:

https://pypi.org/project/django-rq/

However, the `version` in [`setup.py`](https://github.com/rq/django-rq/blob/master/setup.py) in this GitHub repo is only 1.1.1.

There seems to be a mismatch.

**Comment by selwin** [comment]
Sorry about that. It's fixed now.
