### ISSUE TITLE
question:  "finished" column in django admin

### ISSUE THREAD

**Issue by ccurvey** [rq/django-rq#299]
I can't seem to find an answer to this...so I'll just ask.

on the Django admin page for Django-RQ, there's a "finished jobs" column.  I'm assuming that is a count of jobs finished in the last N minutes.

What is N?

**Comment by selwin** [comment]
N is the `result_ttl` value specified when you enqueue a job (see https://python-rq.org/docs/results/) . It defaults to 500.
