### ISSUE TITLE
Support Sentry with sentry-sdk

### ISSUE THREAD

**Issue by Bolayniuss** [rq/django-rq#319]
Since April 2018 Sentry has release it's own package (`sentry-sdk`) to report issues. Using raven is now deprecated. With this package they have dropped the password part of the DSN. Therefore `django-rq` is not compatible with project using `sentry-sdk` as raven internally requires that the DSN is composed of a username *AND*  a password.

`sentry-sdk` has a built-in integration of RQ. According to the doc (https://docs.sentry.io/platforms/python/rq/)  we should just by-pass the registration of sentry in RQ by setting `--sentry_dsn` to an empty string.

**Comment by selwin** [comment]
Support for Sentry-SDK should come in a few weeks time. I'm working on building this into RQ 1.0, which should be released this month.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/333/commits/324b79e0b8c34ed03fc29325acac69d62ba6cbfe
