### ISSUE TITLE
Django admin workers count different

### ISSUE THREAD

**Issue by Yiling-J** [rq/django-rq#322]
Example: on stats page, count is 6, but on workers page, there is only one worker

<img width="1197" alt="screen shot 2019-02-14 at 12 27 19 pm" src="https://user-images.githubusercontent.com/20703055/52762812-10473900-3054-11e9-80a8-2b0426727633.png">
<img width="1212" alt="screen shot 2019-02-14 at 12 27 50 pm" src="https://user-images.githubusercontent.com/20703055/52762817-14735680-3054-11e9-89e0-f9c710ca7a52.png">

**Comment by Yiling-J** [comment]
One possible solution is using rq worker's all() method:
`count = len(Worker.all(queue=queue))`
https://github.com/rq/rq/blob/42d22c5220ec7517e148f9f9dd16121dfac8b5f2/rq/worker.py#L107

**Comment by selwin** [comment]
This is fixed in https://github.com/rq/rq/pull/1056/commits/430dc2e78eb081feac98a58d73cc178a526c6c47

Using `Worker.all()` would be slow when there are large number of workers (in the hundreds). See this https://github.com/rq/django-rq/issues/231

**Comment by Yiling-J** [comment]
Great, that sounds reasonable. I will wait for new rq release and test.

**Comment by Yiling-J** [comment]
Fixed! Thank you

**Comment by dfrankow** [comment]
Cool! Which release was this in?
