### ISSUE TITLE
Gunicorn spawning Django-RQ workers

### ISSUE THREAD

**Issue by jlimas** [rq/django-rq#323]
Not sure if this is the right place to ask about this but suddenly I noticed I had 2 workers in the /jobs/workers/0/ web interface, 1 is idle and ready to pick jobs but there is another one that is busy like if it's stuck. I already tried restarting Gunicorn and the Django RQ worker. 

If I stop the Django RQ worker (running on supervisord) the worker count lowers to 1,  but there is still this other worker in the busy status. It seems to be tied to the Gunicorn process (even on the same PID).

Is there any way to know why or how the Gunicorn / Django process is starting a worker?

**Comment by selwin** [comment]
Workers are run usually run with `./manage rqworker` command. If a worker is registered when your app is run, you must be creating a `Worker` somewhere in your code.
