### ISSUE TITLE
Add page title to admin pages

### ISSUE THREAD

**Issue by rvernica** [rq/django-rq#328]
When browsing the queues, workers, or jobs in the Django admin interface, the pages don't have specific titles. The title shown in the browser for any of these pages is _| Django site admin_.

For comparison, the title shown when browsing the Django Users is _Select user to change | Django site admin_. When viewing a specific user the title is _Change user | Django site admin_.

It would be nice to have specific titles for the queues, workers, and jobs in Django admin.

**Comment by selwin** [comment]
Do you mind opening a PR for this?

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/333/commits/66f3cbe33485286baa0126811843ec4eacb66c7f
