### ISSUE TITLE
django-rq is not compatible with django-redis

### ISSUE THREAD

**Issue by Iliyass** [rq/django-rq#330]
Hello, 

Well, I think django-rq is not compatible with django-redis, because each module requires different version of redis-py

django-redis (requires redis <3) [Issue Link](https://github.com/niwinz/django-redis/issues/342)
django-rq (requires redis>=3)

How you think I can solve this issue ? using both modules 

thanks.

**Comment by selwin** [comment]
django-redis 4.10 (released last October) supports redis-py >= 3. https://github.com/niwinz/django-redis/blob/master/CHANGES.txt
