### ISSUE TITLE
confusion about manage.py -- is it needed?

### ISSUE THREAD

**Issue by williamh** [rq/django-rq#331]
I have looked over the documentation for this package (I'm getting ready to package it for Gentoo) and do not understand the function of manage.py.
It looks to be part of the test suite based on its location (integration_tests/manage.py) and it doesn't appear to be part of what would be installed by pip (it isn't mentioned in setup.py). However, the README seems to imply that it is needed.
Can you please clarify the status of manage.py, and if it should be installed, please give it a name that isn't so generic?

Thanks much for your time.

William

**Comment by selwin** [comment]
`manage.py` is a [Django command](https://docs.djangoproject.com/en/2.1/ref/django-admin/#django-admin-and-manage-py) and is not part of this project.

**Comment by williamh** [comment]
Then why is this here?
Also, your documentation doesn't make clear whether it refers to this script or the django command.
If it is refering to this, it should probably be installed and have a more generic name than manage.py.

Thanks for clarifying this.

https://github.com/rq/django-rq/blob/master/integration_test/manage.py

**Comment by selwin** [comment]
It’s there for testing purposes.

Best,
Selwin
