### ISSUE TITLE
django-rq 2 on pypi but does not match repo

### ISSUE THREAD

**Issue by terencehonles** [rq/django-rq#335]
I'm seeing a v2 on PyPi https://pypi.org/project/django-rq/2.0/ but I'm not finding a changelog here.

Thanks in advance!

**Comment by selwin** [comment]
Sorry about that. I have pushed the latest commit to master.

**Comment by terencehonles** [comment]
Thanks! Was just wondering if there were any backwards incompatible changes I should be watching for, but it seems like not? :)
