### ISSUE TITLE
ImportError: cannot import name FailedQueue

### ISSUE THREAD

**Issue by sikko** [rq/django-rq#352]
It seems that rq - FailQueue has been deprecated and replaced with FailJobRegistry:
https://github.com/rq/rq/releases/tag/v1.0

So i'm getting this error when trying to run my server.

> File "/myproject/virtualenv/lib/python2.7/site-packages/django_rq/queues.py", line 5, in <module>
>     from rq.queue import FailedQueue, Queue

The documentation should mention which version of "rq", django-rq is compatible with.

**Comment by selwin** [comment]
`setup.py` already requires RQ >= 1.0 :)
https://github.com/rq/django-rq/blob/master/setup.py#L17
