### ISSUE TITLE
admin/static not found or sw.js not found.

### ISSUE THREAD

**Issue by bat79a** [rq/django-rq#362]
Hello all.

**My stack is :**
- python:3.7.4-alpine3.10
- django==2.2.5
- django-rq==2.1.0

Without django-rq admin/static are created and there is no probleme.
But when I add django-rq in the INSTALLED_APPS, all the admin/static files are not created.

I found this settings : 
```
RQ_SHOW_ADMIN_LINK = False 
```
in settings.py who solve admin/static problem but I have always the sw.js file in error.

**Here is my settings.py :** 

```python
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# APPS Root
PROJECT_APPS_DIR = os.path.join(BASE_DIR, 'apps')
sys.path.append(PROJECT_APPS_DIR)


############################
# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(PROJECT_APPS_DIR, "my_app_1/static"),
    os.path.join(PROJECT_APPS_DIR, "my_app_2/static"),
)

# path for statics on the server
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# extra places for statics
# STATICFILES_ROOT = []

# MEDIA

MEDIA_ROOT = os.path.join(BASE_DIR, "media/uploads/")

MEDIA_URL = '/srv/media/uploads/'

```

Thx a lot.
Baptiste.

**Comment by selwin** [comment]
This looks more like a Django static configuration issue and not related to django-rq.
