### ISSUE TITLE
Django redis URL setting fails

### ISSUE THREAD

**Issue by alekhrycaiko** [rq/django-rq#364]
On django-rq 1.3.x I've been using the `url` parameter to set my redis-uri; and have had success with this. 

Recently I've tried to upgrade to django-rq 2.1, and I've noticed that my builds fail in a value error stating that the redis uri cannot be found. However, I am certain that I am passing a redis URI. 
Error in question is below:
```
ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)
```

I was able to circumvent this issue by using the `host` and `port` keys on my django-rq settings integration. I was able to get a redis connection working this way for my queues. However,  the failure of the `url` key appears quite mysterious. I am suspicious as to whether a regression may have occurred here?

**Comment by selwin** [comment]
No, the URL parsing is done by `redis-py` itself so if anything's broken, the way you write your URL is probably incompatible with recent versions of `redis-py`.
