### ISSUE TITLE
Make disabling default sentry initialization more obvious

### ISSUE THREAD

**Issue by karech** [rq/django-rq#366]
Currently docs says:
> Disable RQ sentry plugin

> If your project use sentry-sdk, the DSN is not compatible with RQ's sentry plugin (based on raven). In that case you have to disable the sentry plugin by setting --sentry-dsn="".

This is not obvious and looks not good.

Better to allow do it via settings.

**Comment by selwin** [comment]
Actually versions > 2.0 is compatible with `sentry-sdk`, so I'll just have to update the docs about disabling Sentry plugin.

**Comment by karech** [comment]
@selwin Hey, the problem is that passing `--sentry-dsn=""` to disable default sentry integration is not obvious.

For example, in our project we have custom sentry-sdk setup, but django-rq tries to init it anyway if finds SENTRY_SDN in django.settings. 
And passing `--sentry-dsn=""` to django-rq worker is not looking good and obvious.

**Comment by selwin** [comment]
Ah ok, in that case could you please reopen the PR and update the docs accordingly? Thanks

**Comment by karech** [comment]
@selwin I can't reopen it (and this issue), so could you do it please?

Also in PR I've updated [README.rst](https://github.com/rq/django-rq/pull/367/files#diff-88b99bb28683bd5b7e3a204826ead112R321) already.
Do I need to update any other docs?

**Comment by karech** [comment]
Created new issue: https://github.com/rq/django-rq/issues/372
