### ISSUE TITLE
BUG in urls.py: django < 2.0 not supported

### ISSUE THREAD

**Issue by lboc80** [rq/django-rq#389]
this:
https://github.com/rq/django-rq/blob/f63b984f4bc1be7df39128c98c0ccdd89db0c226/django_rq/urls.py#L1

breaks the support for django versions before 2.0.
Tested with `Django==1.11.6` and it does not work, had to revert to `django-rq==2.1.0`

**Comment by hugorodgerbrown** [comment]
@lboc80 as per the release note, support for 1.x has been dropped on master. See [this](https://github.com/rq/django-rq/pull/384#issuecomment-562835371) comment and discussion on the subject - combining support for Django 3.0 and 1.x is quite difficult (without a lot of conditional imports).
