### ISSUE TITLE
NoSuchJobError not handled when requeueing from failed registry

### ISSUE THREAD

**Issue by thomasmatecki** [rq/django-rq#390]
When attempting to _requeue all_ failed jobs in a queue, [`NoSuchJobError`](https://github.com/rq/rq/blob/cf501518534429640a9a6d14e022f9329225e701/rq/exceptions.py#L6) may be raised and not handled gracefully.

It appears to occur in this loop:
https://github.com/rq/django-rq/blob/f63b984f4bc1be7df39128c98c0ccdd89db0c226/django_rq/views.py#L359

I propose we simply catch this exception and set a warning message.

**Comment by selwin** [comment]
PR welcome :)

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/392
