### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by anovas2** [rq/django-rq#396]
rq_scheduler is working for queuing task , but i cant get cron jobs to work. I tried every configuration and I still get the following message. There's not many examples for this.

scheduler.cron(
    '*/5 * * * *',                # A cron string (e.g. "0 0 * * 0")
    func=rp.main(),
    repeat=10,                  # Repeat this number of times (None means repeat forever)
    queue_name='default',    # In which queue the job should be put in

)

```
Traceback (most recent call last):
  File "scheduled.py", line 56, in <module>
    queue_name='default',    # In which queue the job should be put in
  File "/home/anovas/lib/python3.6/site-packages/rq_scheduler/scheduler.py", line 233, in cron
    description=description, timeout=timeout, meta=meta)
  File "/home/anovas/lib/python3.6/site-packages/rq_scheduler/scheduler.py", line 125, in _create_job
    description=description, timeout=timeout, meta=meta)
  File "/home/anovas/lib/python3.6/site-packages/rq/job.py", line 126, in create
    raise TypeError('Expected a callable or a string, but got: {0}'.format(func))
TypeError: Expected a callable or a string, but got: None

```

Any guidance would appreciated it.

**Comment by selwin** [comment]
The `func` argument should be a callable. `scheduler.cron('*/5 * * * *', func=rp.main)`. Also this is not a django-rq issue, next please open the issue in the appropriate repo.
