### ISSUE TITLE
Extend url pattern to include '$' for job_id?

### ISSUE THREAD

**Issue by gowthamk63** [rq/django-rq#397]
Can we extend the url pattern to include '$' symbol? 
I don't see any issue adding the '$' symbol to the url pattern. Please let me know if you have any concerns

The URL that failed for me with a NoReverseMatch exception:
url(r'^queues/(?P<queue_index>[\d]+)/(?P<job_id>[-\w]+)/$',views.job_detail, name='rq_job_detail'),

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/398
