### ISSUE TITLE
Error using custom decorator

### ISSUE THREAD

**Issue by k0t3n** [rq/django-rq#399]
When using a custom decorator for a job the error `The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec ().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY ___ YOU_MUST_EXEC __ () to debug.` occurs.

Example:
```python
import time
from functools import wraps

def simple_decorator(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        print('decorated')
        return f(*args, **kwds)

    return wrapper

@simple_decorator
def simple_job():
    print('doing some stuff')
    time.sleep(5)
```

Starting worker from `python manage.py rqworker`

**Comment by k0t3n** [comment]
Well, running worker with `sudo` solved the problem. Patch for Python is still on review nowadays (https://bugs.python.org/issue33725)

**Comment by k0t3n** [comment]
Related to #375

**Comment by selwin** [comment]
Let's move all discussions about this bug to https://github.com/rq/django-rq/issues/375
