### ISSUE TITLE
Help Needed : Work-horse process was terminated unexpectedly (waitpid returned None)

### ISSUE THREAD

**Issue by arbazkiraak** [rq/django-rq#407]
* What are the common reasons for the following exception, I noticed that below exception halts my scheduler jobs in the middle and put them into a failed state?

```
Moving job to FailedJobRegistry
Work-horse process was terminated unexpectedly (waitpid returned None)
```

The issue has been previously logged at https://github.com/rq/rq/issues/1041 or https://github.com/rq/rq/issues/1014 which indicates the high memory usage on the server could be the reason.

* My tasks spawns so many child processes and utilize high  CPU/Memory usage.
* I had been using celery over the year on the same workspace with the same amount/load of tasks but I had never experienced any `Job` termination due to high memory usage but since I moved to `django-rq` I have been getting above exception more often.
* Is there any way to handle the exception or make it a bypass so that our tasks stay continue. 

```
→ redis-server -v
Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=1660b25130e5921c

rq=1.2.2
django-rq=2.3.0
redis =3.4.1

→ python3 -V
Python 3.7.6
```

**Comment by selwin** [comment]
RQ only terminates work horse if job doesn't finish on time. The fact that `os.waitpid()` returns `None` means the process is already killed by something outside of RQ.

I'm closing this issue because we can't do much if the OS kills the horse process for using too much memory.

**Comment by resulyrt93** [comment]
following environment variable helped me
```
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```
