### ISSUE TITLE
Using the new ScheduledJobRegistry

### ISSUE THREAD

**Issue by JethroMV** [rq/django-rq#409]
Hi, I was very glad to see the native Job Scheduler supported in the 2.3.0 release!
https://github.com/rq/django-rq/releases/tag/v2.3.0

However I'm having trouble enabling it.

I've updated to `django-rq==2.3.0` and `rq==1.3`, but my `python manage.py rqworker` doesn't seem to have the `--with-scheduler` flag.  

I see the flag in the codebase on git https://github.com/rq/django-rq/blob/8ede92d136bc33c355d523158788bf265cfb94d8/django_rq/management/commands/rqworker.py#L40

But it seems the flag is possibly missing from the latest version in pip?

```
$ pip show django-rq
Name: django-rq
Version: 2.3.0
Summary: An app that provides django integration for RQ (Redis Queue)
Home-page: https://github.com/rq/django-rq
Author: Selwin Ong
Author-email: selwin.ong@gmail.com
License: MIT
Location: /home/me/venv/lib/python3.7/site-packages
Requires: redis, django, rq
Required-by: UNKNOWN

$ python manage.py rqworker my_queue --with-scheduler
usage: manage.py rqworker [-h] [--worker-class WORKER_CLASS] [--pid PID]
                          [--burst] [--name NAME] [--queue-class QUEUE_CLASS]
                          [--job-class JOB_CLASS] [--worker-ttl WORKER_TTL]
                          [--sentry-dsn SENTRY-DSN] [--version] [-v {0,1,2,3}]
                          [--settings SETTINGS] [--pythonpath PYTHONPATH]
                          [--traceback] [--no-color] [--force-color]
                          [args [args ...]]
manage.py rqworker: error: unrecognized arguments: --with-scheduler
```
Manually patching the commit that passes that argument through seems to make the scheduler work. It's just not included with 2.3.0 as far as I can tell?

Would love to see https://github.com/rq/django-rq#support-for-rq-scheduler updated for the native scheduler!

**Comment by selwin** [comment]
This PR is already merged. https://github.com/rq/django-rq/pull/405.

I'll try to make a new release this week.
