### ISSUE TITLE
Failed job column in rqstats command

### ISSUE THREAD

**Issue by dangquangdon** [rq/django-rq#416]
I wonder why the `Failed` jobs column isn't shown in the cli command `rqstats`? 

There is `queue["failed_jobs"]` available in the `queue` object for that command, and I can add it myself in my local env. I was just wondering what could be the reason not to show it :question: Like some error or something :question:

**Comment by selwin** [comment]
Because it's not implemented in RQ itself. If you're willing to help, please open a PR for this in RQ's repo https://github.com/rq/rq

**Comment by selwin** [comment]
Upon further investigations, `rqstats` is a management command dprovided by Django-RQ so it should be fixed here. The reason failed jobs are not showing is probably because RQ > 1.x no longer uses `FailedQueue`. Failed jobs are put in `FailedJobRegistry` instead.
