### ISSUE TITLE
Question: Where should periodic tasks be put?

### ISSUE THREAD

**Issue by LucasRoesler** [rq/django-rq#42]
Using rq-scheduler I can define a periodic task but I am not sure where I should put this code.  I have used celery before and it puts such tasks in the settings module, but this is not possible with django-rq because of how `get_scheduler` is defined. Is there a recommended location for infinite periodic tasks that need to be launched with the application?

**Comment by darkpixel** [comment]
The best spot appears to be your AppConfig's ```ready(self)``` function.  (https://docs.djangoproject.com/en/1.8/ref/applications/)

Just to ensure there are no duplicate jobs, I do something like:
```
def ready(self):
    for job in django_rq.get_scheduler('default'):
        job.delete()

    scheduler.schedule(datetime.utcnow(), 'mytask', interval=60*5)
```
