### ISSUE TITLE
Can two different Django projects using django-rq with the same keyspace?

### ISSUE THREAD

**Issue by kegan** [rq/django-rq#424]
If I have more than one Django projects (they are different projects altogether). And I am using django-rq in all these projects.

Can I use the same redis keyspace for all the different projects?

For example, `redis://localhost:6379/0` this uses `keyspace=0`.

Can I use the same django-rq settings for all my different Django projects connecting to the same redis instance.

**Comment by selwin** [comment]
You should have different queue names so your workers don't mix them up.
