### ISSUE TITLE
Set Sentry environment from config variable in job

### ISSUE THREAD

**Issue by ttinjic** [rq/django-rq#427]
Hello,

When I running jobs, Sentry tags : `environment` shows nothing and `server_name` our localhost name even with `environment` and `server_name` arguments in `sentry_sdk.init`.

config :

```
sentry_sdk.init(
 dsn=SENTRY_DSN,
 integrations=[DjangoIntegration(), RqIntegration(), sentry_logging],
 send_default_pii=True,
 max_breadcrumbs=50,
 environment=SENTRY_ENVIRONMENT,
 server_name=SENTRY_ENVIRONMENT,
)
```

when I look at the value of the env var `SENTRY_ENVIRONMENT`, I get
`INFO 2020-05-27 15:00:43,666 [statistics] SENTRY_ENVIRONMENT:tti.test`

however `environment` show nothing and `server_name` tag still show hostname

Do you know how to use the proper environment in a job?

Thanks

**Comment by selwin** [comment]
Not too sure about this, sorry.
