### ISSUE TITLE
Does DjangoRQ "block"?

### ISSUE THREAD

**Issue by taewookim** [rq/django-rq#432]
If I have two scheduled jobs..

Job A => scheduled at 10:00 AM
Job B => scheduled at 10:10 AM

And they are queued on same queue... but job A takes over 30 minutes.. does job B start execution at 10:30 AM?

**Comment by selwin** [comment]
It depends on how many workers you have. If you have only 1 worker, job B starts after job A is finished. If you have two workers, both will be picked up by two different workers and execute simultaneously.
