### ISSUE TITLE
How to Scale Django RQ?

### ISSUE THREAD

**Issue by taewookim** [rq/django-rq#436]
Im working on an architecture that does this
- web dashboard => RQ queue => RQ worker => puppeteer

Currently, writing im hosting RQ queue server/worker in same box as the web dashboard since not too many users, however, i am starting to notice that the RQ worker launching nodejs that connects to a remote puppeteer is starting to eat more memory than I anticipated.

BUT.. since django RQ requires django directory structure to run correctly, how can I separate out RQ worker onto a different machine w/o having to write microservices? 

I thought of having having RQ worker server do SSHFS mount onto dashboard (so i dont have to rip out the code) 

i.e. do something like this

- [server 1] web dashboard => [server 2] RQ server => [server3-5] RQ worker with SSHFS mounted to server1 => [server 6] puppeteer

Problem is, im not sure if this is a good design.

Any ideas?

**Comment by selwin** [comment]
The easiest, simplest and most obvious way would be to have your source code on each machine.
