### ISSUE TITLE
How to scale Django RQ workers that can read from source directory & be able to write to database?

### ISSUE THREAD

**Issue by taewookim** [rq/django-rq#437]
How to "Scale" RQ workers?

I have architecture like this

`uwsgi/django (machine 1) <=> RQ server (machine 1) <=> RQ worker 1...n (machine 1)`

Problem is.. RQ workers are eating up all the CPU so the Django/uwsgi is almost unresponsive during high load

So I want to do something liket his

```
uwsgi/django (machine 1) <=> RQ server (machine 1)
                                -> RQ worker 1 (machine 2)
                                -> RQ worker 2 (machine 3)
                                -> ...
                                -> RQ worker n (machine n-1)

```
Problem is, I'm using Django RQ (django wrapper for RQ).. and the RQ workers are spawned from a specific directory and need to be able to write to database

If I split up the RQ workers into other machines, i need the workers to be able to

read from django source directory
be able to write to Django App database
#2 can be solved with microservice.. however I'm a bit stuck

I can do something like SSHFS but i am not 100% certain if this is a "good" design in terms of scalability, security, and of course, complexity ( i dont' want to keep adding more monitors / software stack).

Of course, I can just have a script that pulls down source code before RQ worker runs but i was wondering if anyone else has better way of doing this.

[edit] Posted in [SO](https://stackoverflow.com/questions/63161593/how-to-scale-django-rq-workers-that-can-read-from-source-directory-be-able-to)

**Comment by selwin** [comment]
This is not an RQ/django-rq issue because it relates to your production deployment. I'm closing this issue.
