### ISSUE TITLE
Use RQ_QUEUES with multiple Redis indexes/dbs

### ISSUE THREAD

**Issue by StriveForBest** [rq/django-rq#450]
Why exactly is this invalid?

```python
RQ_QUEUES = {
    'default': {
        'HOST': 'eon-production.redis.cache.windows.net',
        'PORT': 6380,
        'DB': 0,
        'PASSWORD': 'REDACTED',
        'DEFAULT_TIMEOUT': 30 * 60,  # 30 minutes
        'SSL': True,
    },
    'heavy_load': {
        'HOST': 'eon-production.redis.cache.windows.net',
        'PORT': 6380,
        'DB': 1,
        'PASSWORD': 'REDACTED',
        'DEFAULT_TIMEOUT': 3 * 60 * 60,  # 3 hours
        'SSL': True,
    },
})
```

Is there a way to have different queues use separate redis indexes/dbs?
I tried:
- Providing different `DB`, but that raises `Queues must have the same redis connection.` 
- Adding /1, /2 to the HOST, i.e. `'HOST': 'eon-production.redis.cache.windows.net/1'`

What's the good practice to have async tasks queue up in different queues? If i provide the same db, doesn't it mean that both queues are going through the same redis connection and the task in my `default` queue will have to wait until the task from my `heavy_load` queue gets consumed?

**Comment by selwin** [comment]
You're allowed to separate queues using their own DB's. What you can't do however, is have a worker that runs on different queues with different DBs.

Meaning you'd need to have a worker for `heavy_load` and a separate worker for `default`. Hope this is clear.

**Comment by StriveForBest** [comment]
> You're allowed to separate queues using their own DB's. What you can't do however, is have a worker that runs on different queues with different DBs.
> 
> Meaning you'd need to have a worker for `heavy_load` and a separate worker for `default`. Hope this is clear.

Could you provide an example, please? How would I set it up?

**Comment by selwin** [comment]
Run `./manage.py rqworker heavy_load` to run worker for the `heavy_load` queue. Run `./manage.py rqworker default` for the regular one.
