### ISSUE TITLE
Job is always marked as enqueued_at=None and doesn't seem to get registered

### ISSUE THREAD

**Issue by BrianWClausen** [rq/django-rq#456]
I've been trying to solve this issue for the better part of two days now, and I just can't seem to find out what is wrong.

Whenever i try to run a job with django_rq/rq-scheduler I get a response with an ID stating that enqueued_at=None and the job never seems to be enqueued or run. 

**Relevant packages:**
Python 3.7
Django==2.2.9
redis==3.5.0
rq==1.6.1
rq-scheduler==0.10.0
django-rq==2.4.0

**Below is a log for the docker-container, where everything seems to be starting just fine:**
django_1   | [2020-11-25 14:45:25 +0000] [8] [INFO] Starting gunicorn 19.9.0
django_1   | [2020-11-25 14:45:25 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
django_1   | [2020-11-25 14:45:25 +0000] [8] [INFO] Using worker: sync
django_1   | [2020-11-25 14:45:25 +0000] [12] [INFO] Booting worker with pid: 12
django_1   | [2020-11-25 14:45:25 +0000] [13] [INFO] Booting worker with pid: 13
django_1   | 15:45:32 Registering birth
django_1   | 15:45:34 Worker rq:worker:3fa82daacc9d49d688b21be81882bc6a: started, version 1.6.1
django_1   | 15:45:34 Subscribing to channel rq:pubsub:3fa82daacc9d49d688b21be81882bc6a
django_1   | 15:45:34 *** Listening on default...
django_1   | 15:45:34 Cleaning registries for queue: default

**Response when adding a simple job through shell**

`import django_rq`
`from datetime import datetime`
`scheduler = django_rq.get_scheduler('default')`
`scheduler.enqueue_at(datetime.now(), print, "hello world")`
`Job('38409354-545f-493b-be5d-2b50ce3362b2', enqueued_at=None)`

**Running scheduler.get_jobs() produces an empty list no matter what.**
**Running the manage.py rqstats command shows an available worker, but no tasks in any of the columns**

I don't expect this to be solved, but if someone could point me in the right direction or suggest a way of debugging the problem, I would be grateful.

**Comment by selwin** [comment]
If you're using `rq-scheduler` as a separate project, make sure that you also run the `rqscheduler` management command.

If you're using the scheduling component built into RQ since version 1.2.0, you need to run `rq worker` with `--with-scheduler` flag enabled. Docs here: https://python-rq.org/docs/scheduling/

**Comment by gdmen** [comment]
> If you're using `rq-scheduler` as a separate project, make sure that you also run the `rqscheduler` management command.
> 
> If you're using the scheduling component built into RQ since version 1.2.0, you need to run `rq worker` with `--with-scheduler` flag enabled. Docs here: https://python-rq.org/docs/scheduling/

Check out this comment + the rest of the thread: https://github.com/rq/rq-scheduler/issues/51#issuecomment-536652049
