### ISSUE TITLE
rqworker --with-scheduler won't schedule jobs without rqscheduler also running

### ISSUE THREAD

**Issue by ptrck** [rq/django-rq#476]
I'm running `./manage.py rqworker --with-scheduler` but unless I also run `./manage.py rqscheduler` no jobs are being scheduled when using `enqueue_at`.

Am I missing something here?

**Comment by lepture** [comment]
There are two types of scheduled jobs in django-rq. One is created by rq-scheduler, and one is created by rq.

`rq` has a built-in scheduler now. If you are using:

```py
from django_rq import get_queue

queue = get_queue()
queue.enqueue_at(datetime, function)
```

This will use the `rq` built-in scheduler, it will work with `rqworker --with-scheduler`

If you are using:

```py
from django_rq import get_scheduler
```

You are using `rq-scheduler`, and it must work with `./manage.py rqscheduler`.

And in admin dashboard, there is a stats for "scheduled jobs", this "scheduled jobs" count will only show jobs created by rq's built-in scheduler.

----

I think django-rq should just remove the `get_scheduler` method.

**Comment by selwin** [comment]
> I think django-rq should just remove the get_scheduler method.

I would eventually, but at the moment there are some features that rq-scheduler has that RQ's built in scheduler doesn't so we'll keep it there for now.

**Comment by marcy-buccellato** [comment]
> > I think django-rq should just remove the get_scheduler method.
> 
> I would eventually, but at the moment there are some features that rq-scheduler has that RQ's built in scheduler doesn't so we'll keep it there for now.

Is one of those features the `retry` functionality? I'm wondering if I can use [the retry functionality](https://python-rq.org/docs/exceptions/#retrying-failed-jobs) with django-rq.

**Comment by selwin** [comment]
I think we can start deprecating rq-scheduler by removing it from the docs.

And yes, if you run rqworker with —with-scheduler flag, Retries should work.

**Comment by hoenie-ams** [comment]
Maybe a stupid question: where exactly in the Django app should we add the scheduled tasks? I the AppConfig's 'ready' method or in a '__init__.py' file?

**Comment by gdmen** [comment]
> Maybe a stupid question: where exactly in the Django app should we add the scheduled tasks? In the AppConfig's `ready()` method or in a `__init__.py` file? Or should we subclass `rqworker` like in [rq/rq-scheduler#51 (comment)](https://github.com/rq/rq-scheduler/issues/51#issuecomment-362352497)?

Check out this comment + the rest of the thread: https://github.com/rq/rq-scheduler/issues/51#issuecomment-536652049

**Comment by hoenie-ams** [comment]
Thanks @gdmen, I've subclassed it like in the solution you referred to and it works like a charm.

**Comment by DhavalGojiya** [comment]
Does anyone know how to use **cron string-based task scheduling** with just the `django_rq` library, without relying on the `rq_scheduler` library?

I understand that we now have the built-in `--with-scheduler` argument, which listens for tasks scheduled using the following code:

```python
from django_rq import get_queue
q = get_queue("default")
q.enqueued_at(<TIME>, <FUNC>)
```

But how can we achieve this using **cron strings** without using the `rq_scheduler` library?
