### ISSUE TITLE
Cannot run jobs asynchronously [solved]

### ISSUE THREAD

**Issue by jej** [rq/django-rq#486]
Hi,

Maybe I don't understand the concept of RQ/async... here is my test:

```
def long_running_func1(*args, **kwargs):
    while True:
        print(1)
        time.sleep(1)
        print(time.time())
def long_running_func2(*args, **kwargs):
    while True:
        print(2)
        time.sleep(1)
        print(time.time())
def long_running_func3(*args, **kwargs):
    while True:
        print(3)
        time.sleep(1)
        print(time.time())

---

queue = django_rq.get_queue('default', autocommit=True, is_async=True, default_timeout=30)
queue.enqueue(long_running_func1)
queue.enqueue(long_running_func2)
queue.enqueue(long_running_func3)

---

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '...',
        'ASYNC': True,
    },
}
```
Running with and without systemd. Last versions for everything.

Output is:
```
1
1620331485.5410786
1
1620331486.5423558
1
1620331487.5437515
1
1620331488.5449352
1
.../...
2
1620331490.547702
2
1620331491.5488412
2
1620331492.5500293
.../...

```

The jobs are stopped after the 30s timeout, but I could never run them all together. They are queued and executed sequentially. I followed the readme, went in the code, went to RQ repo, but nothing helps.
Any idea what I am missing?
Thanks for your help.

**Comment by jej** [comment]
Well, it's more or less solved. I was testing at the same time Django-Q (https://django-q.readthedocs.io/en/latest/index.html), which just launchs one worker and spawns itself on available cores. I was expecting for the same feature. Not really a problem, I just ran many instances and it works the same. I will test a bit further now...
Thx anyway.

**Comment by jej** [comment]
Nice to separate with the system layer indeed... Going for RQ then...
Thx for this work.

**Comment by daufinsyd** [comment]
Hi @jej 
I face the same "issue", what do you mean with 'I just ran many instances and it works the same' ? Do you mean to create separate queues and randomly schedule stuff on each ?
Thanks  :)

**Comment by jej** [comment]
If I remember well this issue...

Yes, I had to run several queues on different workers, to have all cpu buzy and tasks run in parallel. "randomly schedule" or not.

**Comment by daufinsyd** [comment]
ok, Thank you :)
