### ISSUE TITLE
Missing Cache-Control

### ISSUE THREAD

**Issue by th3hamm0r** [rq/django-rq#492]
Currently the django-rq views don't use any kind of cache control decorators, so if you add django's per-site cache logic using the `UpdateCacheMiddleware` and `FetchFromCacheMiddleware` (https://docs.djangoproject.com/en/stable/topics/cache/#the-per-site-cache) you will end up caching all django-rq-routes with the configured caching.
This results in unreliable output, eg. showing wrong counts, tasks,...

I think all django-rq views should use the `@never_cache`-decorator (https://docs.djangoproject.com/en/stable/topics/http/decorators/#django.views.decorators.cache.never_cache) due to the volatility of its stats.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/498
