### ISSUE TITLE
Error 111 connecting to 38.106.79.194:6379. Connection refused.

### ISSUE THREAD

**Issue by nadermx** [rq/django-rq#497]
Hi, I'm currently trying to set up a remote worker via django rq, but when I run the this command, I get connection refused
```
python manage.py rqworker video
Error -2 connecting to redis://38.106.79.194:6379. Name or service not known.
```

My settings file looks like this

```
    'video': {
        'HOST': '38.106.79.194',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': 'longpassword',
        'DEFAULT_TIMEOUT': -1,
    },
```

On the remote server I also set the bind to `0.0.0.0 ::1` in the redis config as well as opended up the ufw port 6379, yet I'm still getting connection refused.  Any help would be appreciated

**Comment by nadermx** [comment]
It seems, that if I try in the server as well to launch a rq worker, instead of remotely, it still gives the Authentication required, even though it's in the settings.py file.

Is it not pulling the password argument? As when testing a redis-cli with auth, it ping'd perfectly.

**Comment by selwin** [comment]
This is not a RQ or django-rq issue, it's how your configuration is setup.
