### ISSUE TITLE
Enqueue a job but delay its execution by a certain time

### ISSUE THREAD

**Issue by BigglesZX** [rq/django-rq#500]
Firstly, thanks for this super useful package. It's been several years since I last used job queues with Django, and it's amazing how things have moved on and what great tools are now available.

Hopefully simple question – I have a webhook view in Django which, when called by an external service, enqueues a job with `.delay()`. However for reasons not worth getting into, I'd like to ensure that the job is not executed for at least a couple of minutes, even if there's a worker available to process it. Is there a means to do this with rq / django-rq's existing API?

If not, can anyone think of a sensible alternative strategy? I only have one worker in this project, so while I could just `sleep()` inside the job itself, I'd rather not as that would tie up the worker unnecessarily. Should I be looking at spawning a thread/subprocess which could `sleep()` before enqueuing the job? That's off-topic for rq / django-rq obviously, but if anyone thinks that's the way to go, I'll research it.

Thanks in advance!

**Comment by neel-bp** [comment]
why not use `enqueue_in(timedelta(seconds=<x>),func)` this will enqueue the job in given time
also make sure to run the worker with
`python3 manage.py rqworker --with-scheduler`

**Comment by BigglesZX** [comment]
Aha, I'd missed the mention of Scheduler in the README, and its implications. This is great, thanks @neel-bp!

For future readers, I found [this helpful issue](https://github.com/rq/django-rq/issues/476#issuecomment-865028353) which explains the difference between rq's built-in scheduler and the separate rq-scheduler package.

My delayed-retrying solution looks something like this:

```python
from datetime import timedelta
from django_rq import get_queue, job

@job
def task_name(arg1, arg2, retry=0):
    # ...
    if failure_condition and retry < 3:
        wait = (retry + 1) * 60
        queue = get_queue()
        queue.enqueue_at(
            timedelta(seconds=wait),
            task_name, args=(arg1, arg2, retry + 1))
        return
    else:
        # Too many retries
        # ...
        return
```

The detail that took a couple of go-arounds for me to realise is that the second argument to `enqueue_at` should be a function that exists in the current _module_ (i.e. a job definition or one that's been imported from another module) – a reference to a locally defined function or a lambda won't work.
