### ISSUE TITLE
Django-RQ eating all memory - how i can optimize the footprint?

### ISSUE THREAD

**Issue by Simonefardella** [rq/django-rq#501]
Hi guys, i'm using django RQ in my application for notify my frontend web-application using websockets and read using a scheduler some SNMP devices.

I'm starting a total of 11 workers on my production machine (2GB RAM and 2CPU), what i see is that the django-rq (python-rq in fact) it eats up to the 40/50% of the memory.

![image](https://user-images.githubusercontent.com/5062855/126611611-93ebce82-416e-4739-aa16-5acfb07e0583.png)

This represent a issue for me: my machines are constrained about resources and adding some ram is *totally* out of question.

Now, consider that i'm pushing the jobs in the default worker in this way:

Models: 

    def save(self, *args, **kwargs):
    if self._state.adding: 
        from myapp_websockets.notifiers.insert_measurement_notifier import \
            WSInsertMeasurementNotifier
        WSInsertMeasurementNotifier().notify_group(self)

    super(DeviceMeasurement, self).save(*args, **kwargs)

InsertMeasurementNotifier.py:

    django_rq.enqueue(self._channel_group_send,
                              description='Default group Notifier Task',
                              result_ttl=0)  # Enqueue to django_rq default queue

In the other hand, the Background process is a management command that i'm using to read the SNMP devices (they are 300 devices) and does basically the same things: it push to the queue the device job to read of every device every minute.

**Comment by selwin** [comment]
So RQ itself doesn't consume much memory but rather it's your job that you should optimize.
