### ISSUE TITLE
workers count on admin page not reflected correctly

### ISSUE THREAD

**Issue by marsha97** [rq/django-rq#504]
We had 21 workers before, and changed to 16 workers only. We checked the daemon with `systemctl status` and it was 16, but in admin it was  still 21.

**Comment by selwin** [comment]
Yeah, sometimes the worker count may appear out of sync. Worker registries are periodically cleaned up (if I remember correctly once every 15 minutes) by one of RQ's workers so if you're changing the worker count and monitoring it via dashboard, the right worker count may not show up immediately.

The solution is to call [clean_worker_registry(queue)](https://github.com/rq/rq/blob/6bfd47f735de3f297ba3c8f59d5e2dcfa1987107/rq/worker_registration.py#L50) before displaying the worker count in [this view](https://github.com/rq/django-rq/blob/master/django_rq/views.py#L231).

Mine opening a PR for this?

**Comment by marsha97** [comment]
> Yeah, sometimes the worker count may appear out of sync. Worker registries are periodically cleaned up (if I remember correctly once every 15 minutes) by one of RQ's workers so if you're changing the worker count and monitoring it via dashboard, the right worker count may not show up immediately.
> 
> The solution is to call [clean_worker_registry(queue)](https://github.com/rq/rq/blob/6bfd47f735de3f297ba3c8f59d5e2dcfa1987107/rq/worker_registration.py#L50) before displaying the worker count in [this view](https://github.com/rq/django-rq/blob/master/django_rq/views.py#L231).
> 
> Mine opening a PR for this?

Ok noted on this, will try to look into it

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/516
