### ISSUE TITLE
Unexpected ignoring of SSL_CERT_REQS when using URL method of configuring RQ_QUEUES

### ISSUE THREAD

**Issue by paltman** [rq/django-rq#508]
Spent a good bit of time tonight debugging an issue with Heroku's self-signed certs on their redis instances.  Finally determined what I needed to do was to turn off the SSL verification.  I found a setting that I was supposed to pass to my queue config, `SSL_CERT_REQS: None`, but was getting seemingly no change.

I went digging into [the code](https://github.com/rq/django-rq/blob/4a1993e06558ed0cc4a5e2957500d0e8f94b63bc/django_rq/queues.py#L79) to find that the `URL` param was causing a early exit from the `get_redis_connection` function.

This wasn't obvious from the docs and it would be nice if `SSL_CERT_REQS` is set, that the internals of the `get_redis_connection` would do the right thing making it easier and less confusing for the developer.

For those arriving here from Google, as I imagine this is a common enough issue given the nature of Heroku's self-signing certs, what I did in settings was to use `urlparse` and then specify each piece instead of using `URL`:

```python
import os
from urllib.parse import urlparse

RQ_DATABASE = 1
REDIS_URL = os.env.get("REDIS_URL", "redis://localhost:6379")

url = urlparse(REDIS_URL)

RQ_QUEUES = {
    "queue_one": {
        "HOST": url.hostname,
        "USERNAME": url.username,
        "PASSWORD": url.password,
        "PORT": url.port,
        "DB": RQ_DATABASE,
        "SSL": True,
        "SSL_CERT_REQS": None,
    },
    "queue_two": {
        "HOST": url.hostname,
        "USERNAME": url.username,
        "PASSWORD": url.password,
        "PORT": url.port,
        "DB": RQ_DATABASE,
        "SSL": True,
        "SSL_CERT_REQS": None,
    }
}
```

**Comment by paltman** [comment]
I think it might be as simple as changing:

```python
    if 'URL' in config:
        return redis_cls.from_url(config['URL'], db=config.get('DB'))
```

to

```python
    if 'URL' in config:
        return redis_cls.from_url(config['URL'], db=config.get('DB'), ssl_cert_reqs=config.get('SSL_CERT_REQS', 'required'))
```

**Comment by paltman** [comment]
If this looks good to folks, happy to put together a PR

**Comment by paltman** [comment]
was easy enough so went ahead and made one but I realize I might be missing loads of context that would make this incorrect.  just let me know and I'll whip it into shape. thanks!

**Comment by feigner** [comment]
This works wonderfully, except when I attempt to use a `URL` to point at a non-SSL URL, the underlying Redis connection complains about an unknown `ssl_cert_reqs` argument. I feel like this option should only be applied if `config.get('SSL')` is set.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/509/files

**Comment by antoinesion** [comment]
I think @feigner raised an important point here. I had that issue today when I deployed my app to Heroku with the new 2.5.0 release:

```
return self.connection_class(**self.connection_kwargs)
TypeError: __init__() got an unexpected keyword argument 'ssl_cert_reqs'
```

As I use a non-SSL URL (i.e. `redis://...` and not `rediss://`), `redis-py` is using [this connection class](https://github.com/redis/redis-py/blob/fea7b85dde375a228f485d27737de66592b28848/redis/connection.py#L500) which does not accept a `ssl_cert_reqs` argument...

As @feigner said, `ssl_cert_reqs ` should be applied only if `config['SSL']` is set or if `config['URL']` starts with `rediss://` (a SSL URL).

**Comment by feigner** [comment]
Thanks @antoinesion. I wasn't able to overcome this issue directly. Thankfully I was able to use the `USE_REDIS_CACHE` option to point at my already-defined `rediss://...` connections.

**Comment by selwin** [comment]
Do you mind opening a PR for this @antoinesion @feigner ?

**Comment by antoinesion** [comment]
Yes, I'll try to open a PR today!
