### ISSUE TITLE
Document REDIS_CLIENT_KWARGS

### ISSUE THREAD

**Issue by edmorley** [rq/django-rq#510]
Hi!

django-rq currently supports passing custom options to the Redis client by specifying `REDIS_CLIENT_KWARGS` inside the `RQ_QUEUES` config entry:
https://github.com/rq/django-rq/blob/11527cfdc6408b9c23c24255f8684b61860cc671/django_rq/queues.py#L127

For example:

```py
RQ_QUEUES = {
    'default': {
        // ...
        'REDIS_CLIENT_KWARGS': {
                'ssl_cert_reqs': None
        },
    },
```

However this is not currently documented:
https://github.com/rq/django-rq/search?q=REDIS_CLIENT_KWARGS

It would be great to add an example of this to the README :-)

**Comment by selwin** [comment]
Do you mind opening a PR for this?

**Comment by edmorley** [comment]
I don't personally use this library, so probably will struggle to find the time, sorry (I was reporting it since I'd seen in a support ticket).
