### ISSUE TITLE
Reject unknown config options in RQ_QUEUES

### ISSUE THREAD

**Issue by edmorley** [rq/django-rq#511]
Hi!

I've just been debugging a Heroku support ticket, where the app was using django-rq, and was having errors connecting to Redis, as the `"ssl_cert_reqs": None` wasn't being honoured.

The config used was similar to:

```
RQ_QUEUES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "URL": os.environ.get("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "ssl_cert_reqs": None
            },
        }
    },
}
```

The reason the above config doesn't work is because it is in something close to Django config format (normally used under `CACHES`), rather than the format that django-rq expects under `RQ_QUEUES`.

I suspect this confusion may have arisen, since the django-rq README says (https://github.com/rq/django-rq#installation):
> Configure your queues in django's settings.py \***(syntax based on Django's database config)**\*:

Whilst the fix in this case is easy (either adjust `RQ_QUEUES` to use the expected format, or use `CACHES` + `USE_REDIS_CACHE`), it would be great to make this type of misconfiguration easier to debug.

I would suggest:
1. Removing the `syntax based on Django's database config` reference from README
2. Having django-rq error on unknown config options inside `RQ_QUEUES` (and for bonus points, detecting `OPTIONS` specifically and giving an error like "it looks like you're using Django options here, see: https://github.com/rq/django-rq#support-for-django-redis-and-django-redis-cache)"

Many thanks :-)

**Comment by selwin** [comment]
I took out `(syntax based on Django's database config)` from README. Feel free to open another PR to improve this.

**Comment by edmorley** [comment]
@selwin Thank you :-)
