### ISSUE TITLE
How to gracefully reload django rqworker

### ISSUE THREAD

**Issue by ifduyue** [rq/django-rq#52]
Sorry for asking question in an issue tracker. But I am wondering how to gracefully reload django rqworker without losing any running jobs.

Thanks in advance!

**Comment by joelfranco** [comment]
Hi,

**Comment by joelfranco** [comment]
I'm trying to restart the worker gracefully, but the job is interrupted and the worker quickly restarted.

The worker runs in a system user service as below:

```
[Unit]
After = v@%i.service

[Service]
Type=simple
WorkingDirectory=/home/r27/r27/web
Environment="DISPLAY=:%i"
ExecStart=/home/r27/r27/.venv/bin/python3 manage.py rqworker
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true
Restart=always

[Install]
WantedBy = default.target

```
How can I restart the worker wait for the current job to finish before it restart?

Thank you
