### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by tomhamiltonstubber** [rq/django-rq#555]
Hi folks,

Can we get a release please?

**Comment by samuelcolvin** [comment]
Release on this would be great. 

@selwin please can I propose that we add @tomhamiltonstubber as a collaborator on this organisation? Tom works with me and I can vouch for him both as a good developer and a nice person.

**Comment by selwin** [comment]
Hey guys, sorry I just saw this message. Will work on a release this week.

@samuelcolvin I don’t mind adding collaborators, but I’d prefer adding people who have a prior track record of contributing. If @tomhamiltonstubber can start reviewing and creating PR’s, perhaps sometime in the near future 😀

**Comment by samuelcolvin** [comment]
Makes sense, thanks for doing a release.

**Comment by selwin** [comment]
Done. https://pypi.org/project/django-rq/2.6.0/
