### ISSUE TITLE
Support for default failure result TTL

### ISSUE THREAD

**Issue by muhammedabad** [rq/django-rq#568]
Hi,

Does django-rq provide support for the `failure_ttl` setting specified [here](https://python-rq.org/docs/) ?

EDIT: I see that the `FailedJobRegistry` class in RQ has a cleanup method which might be a workaround if the failure TTL setting is not directly supported:

![image](https://user-images.githubusercontent.com/1520135/217197371-51d1e0d2-f3bb-4eb4-9b8c-43a28b7b82ce.png)

**Comment by selwin** [comment]
Yes, `get_queue()` returns a `Queue` object and `failure_ttl` is one of its arguments.

**Comment by Smona** [comment]
Should this really be closed? I would expect there to be a `DEFAULT_FAILURE_TTL` setting like there is `DEFAULT_TIMEOUT` and `DEFAULT_RESULT_TTL`.
