### ISSUE TITLE
Page <h1> redundancy in text

### ISSUE THREAD

**Issue by niccolomineo** [rq/django-rq#580]
While the `browse_queue/` page metatitle is "Queues", the `<h1>` for the same page is "RQ Queues", which is a repetition too ("Q" already stands for "Queue(s)". I feel "Queues" should be the text for the `<h1>` as well - thus without "RQ".

"Redis Queues" could also be appropriate for both.

What do you think?

**Comment by selwin** [comment]
`Queues` is good  😀

**Comment by niccolomineo** [comment]
I am submitting a PR tomorrow
