### ISSUE TITLE
New v1.14 of RQ breaks django-rq

### ISSUE THREAD

**Issue by dennmat-hurdle** [rq/django-rq#589]
https://github.com/rq/rq/releases/tag/v1.14

I was getting: ImportError: cannot import name 'use_connection' from 'rq'
In: django_rq/management/commands/rqworker.py, line 5, in <module>

I fixed it for myself by pinning the rq version to 1.13

Thought I'd log it here to bring light to it. Thanks!

**Comment by jeremystretch** [comment]
It appears that `use_connection()` was [intentionally removed](https://github.com/rq/rq/pull/1859) from rq v1.14. This was called out in that PR as breaking django-rq but the change unfortunately was not communicated in the release notes.

**Comment by selwin** [comment]
This was already fixed in version 2.8.0 released a few days ago. https://pypi.org/project/django-rq/2.8.0/
