### ISSUE TITLE
RQ 1.14.0 breaks django-rq (use_connection)

### ISSUE THREAD

**Issue by orokusaki** [rq/django-rq#592]
Hey @selwin, et al,

`rq==1.14.0` breaks `django-rq==2.7.0`, due to the [importation](https://github.com/rq/django-rq/blob/v2.7.0/django_rq/management/commands/rqworker.py#L5) / [use](https://github.com/rq/django-rq/blob/v2.7.0/django_rq/management/commands/rqworker.py#L124) of the previously-deprecated, now-removed `use_connection`.

I stumbled [this old note in the 1.13 ~ 1.14 diff](https://github.com/rq/rq/compare/v1.13.0...v1.14#diff-05d8841ed08aadc3ecde4f60e26f0da1a7d1a65b67c1a4d9d774f869896b1e26L6) about using the `Connection` context manager, in lieu of the `use_connection` function, and then landed on the [current docs about connections](https://python-rq.org/docs/connections/#connection-contexts-precise-and-concise), and I thought it'd be best to make an issue here for discussion, before attempting to make a patch for this.

  1. is the approach in the aforementioned docs up to date and fully relevant?
    a. would you accept a patch to update this module to reflect that?
    b. do you recommend any other changes to go along with this?
  2. are there other changes you know of that would be required, in order to support `rq==1.14.0`?

**Comment by selwin** [comment]
@orokusaki thanks for catching this.

1. Do you mind making a PR to change `use_connection` to the `Connection` context manager?
2. No, as far as I know there's no other breaking changes.
Thanks!

**Comment by selwin** [comment]
Actually there's already a draft PR for this. https://github.com/rq/django-rq/pull/583/files

**Comment by titanmichael** [comment]
@selwin - that's excellent news - I just got back in front of my screen. Let me know if you need any more help; I'd love to make a PR for something or another.

**Comment by orokusaki** [comment]
@selwin - that's excellent news - I just got back in front of my screen. Let me know if you need any more help; I'd love to make a PR for something or another.

**Comment by selwin** [comment]
I think that PR is good to do. I'll merge and make an emergency release.

**Comment by selwin** [comment]
This was already fixed in version 2.8.0 released a few days ago. https://pypi.org/project/django-rq/2.8.0/
