### ISSUE TITLE
RQ scheduler broken with recent RQ version

### ISSUE THREAD

**Issue by dicknetherlands** [rq/django-rq#596]
Since version 2.7.0 I am unable to use the scheduler in django-rq. It claims rq_scheduler is not installed but it definitely is!

  File "/home/runner/work/....../jobs/rq/apps.py", line 13, in ready
    scheduler = django_rq.get_scheduler(name=redis_queue_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/django_rq/queues.py", line 341, in get_scheduler
Error:     raise ImproperlyConfigured('rq_scheduler not installed')
django.core.exceptions.ImproperlyConfigured: rq_scheduler not installed

**Comment by dicknetherlands** [comment]
This can be demonstrated with rq-1.14.0, rq_scheduler-0.13.0, django-rq-2.8.0, on the default install of django-rq as per its README.

**Comment by dicknetherlands** [comment]
Downgrading RQ to 1.13.0 fixes it. So looks like an issue with RQ 1.14.0 specifically.

**Comment by selwin** [comment]
Hey, RQ scheduler 0.13.1 was released a few days ago. https://pypi.org/project/rq-scheduler/0.13.1/
