### ISSUE TITLE
ImportError: cannot import name 'ColorizingStreamHandler' from 'rq.utils'

### ISSUE THREAD

**Issue by Gyakusetsu** [rq/django-rq#616]
**My current solution:**

Looks like something broke in rq >= 1.14.0
- `pip install rq==1.13.0`

**Comment by selwin** [comment]
This should already be fixed in newer version of django-rq.

**Comment by oleksandr-luxmedien** [comment]
Greetings, I'm using django-rq == 2.10.2 and rq == 1.16.2, and I am having the same error.
