### ISSUE TITLE
Allow Specifying Default Serializer for Django-RQ Queue

### ISSUE THREAD

**Issue by sophcass** [rq/django-rq#626]
## Description
We are currently using `django-rq` alongside Redis Queue (RQ). In our setup, we've opted to use the `JSONSerializer` instead of the default pickle serializer. The reason behind this choice is the potential versioning issues that can arise from using pickle.

## Details
We've successfully configured our setup to use the `JSONSerializer` for processing jobs in the queue. However we've run into an issue when it comes to utilising the `django-rq` admin dashboard while also using the `JSONSerializer`.

The challenge we face is that `django-rq` isn't aware of the serializer we've chosen, and as a result, it doesn't specify the serializer when fetching information to be displayed in the admin dashboard. As a result, the dashboard becomes somewhat limited and less useful for us.

The admin dashboard feature was one of the primary reasons we have adopted `django-rq`, and we are eager to continue leveraging it while also using the `JSONSerializer` for our jobs.

## Proposed Solution
We would like to propose opening a PR to enhance `django-rq`'s functionality. Specifically, to enable users to specify their desired default serializer when they initially set up the Redis queue. This enhancement would simplify our configuration process, ensuring that we don't need to set the serializer in multiple places when setting up the Redis queue via `django-rq` and also it would allow us to utilise the admin dashboard in conjunction with `JSONSerializer`.

If you are happy for us to make these changes, we can get to work on a PR to implement them! Let us know!

**Comment by sophcass** [comment]
@selwin it would be great to hear your thoughts about this proposition, so that we can start working on it.

**Comment by selwin** [comment]
Fixed in https://github.com/rq/django-rq/pull/630
