### ISSUE TITLE
Unconstrained rq version in setup.py breaks django-rq v2.x

### ISSUE THREAD

**Issue by danloveg** [rq/django-rq#682]
I noticed with [the recent release of RQ](https://github.com/rq/rq/releases/tag/v2.0) that my container using django-rq now starts to fail a worker with the command:

```shell
python manage.py rqworker default
```

I am getting this error in my Docker container:

```
2024-10-28 13:52:31   File "/usr/local/lib/python3.10/site-packages/django_rq/management/commands/rqworker.py", line 5, in <module>
2024-10-28 13:52:31     from rq import Connection
2024-10-28 13:52:31 ImportError: cannot import name 'Connection' from 'rq' (/usr/local/lib/python3.10/site-packages/rq/__init__.py)
```

If I run a `pip freeze` I see these lines:

```
django-rq==2.10.2
rq==2.0.0
redis==5.2.0
```

I believe this is due to the version in `setup.py` being constrained to any version `>=1.4` ([see here](https://github.com/rq/django-rq/blob/025a53f379e48a9d5483421260d8052f143169bf/setup.py#L17)) so the latest version of rq is being installed in v2.x even though support has not been added yet.

**Comment by Suijn** [comment]
happened also for me, django-rq 2.8.1

**Comment by FatemeFouladkar** [comment]
happend to me too. I just specified the RQ version to be less than 2.0.0 to keep things working.

> django-rq = "^2.10.2"
rq = ">=1.14,<2.0.0"

**Comment by danloveg** [comment]
I can make a pull request to fix this issue but I don't think it makes sense to merge the change into the `master` branch. It may be that a separate branch needs to be maintained for versions of django-rq before v3.0.0.

**Comment by morezco** [comment]
Adding our 2¢, we got the same error running django-rq==2.10.2 without a version set for rq. Locking rq on 1.16.2 resolved the issue.

**Comment by kaimcpheeters** [comment]
@selwin Given that 3.0.0 was only released 2 days ago would it be possible to get a 2.10.3 release that fixes this issue?

We had `django-rq==2.8.1` pinned and are experiencing the same error.

**Comment by selwin** [comment]
Will try to do so this weekend. In the meantime, pinning your RQ version should also fix the issue.

**Comment by selwin** [comment]
Done. https://pypi.org/project/django-rq/2.10.3/

**Comment by Lapeth** [comment]
It would be prudent to also pin `rq` in the current `master`, so future releases of `rq` doesn't break django_rq 3.x
