### ISSUE TITLE
Autoconfigure logging for the ``rqscheduler`` management command also

### ISSUE THREAD

**Issue by spapas** [rq/django-rq#91]
The `rqworker` management command has a section that setups logging for `rq.worker` if it hasn't been configured in `settings.py`. I recommend adding a similar section to the `rqscheduler` management command, something like: 

```
logger = logging.getLogger('rq_scheduler')
if not logger.handlers:
    logger.setLevel(logging.DEBUG)
    formatter = logging.Formatter(fmt='%(asctime)s %(message)s',
                                  datefmt='%H:%M:%S')
    handler = ColorizingStreamHandler()
    handler.setFormatter(formatter)
    logger.addHandler(handler)
```

Both management commands should have a similar behavior since users (like myself) may be running `python manage.py rqscheduler` and be confused on the lack of any output (if they haven't explicitly setup loggers for `rq_scheduler`). 

Is there a reason for not configuring loggers on `rqscheduler` ?

If you want I could provide a patch - however I wanted first to start a discussion for that. 

Thanks !

**Comment by selwin** [comment]
Yes, please provide a patch to setup default logger configuration for `rqscheduler` command. Thanks!
